Repository BF-FrontEnd-class-2025/group-2-guess-number-game, pull requests merged in 2025-03, with the labels that each got.

#7 add wireframe
  planning/design.md
  planning/wireframe.png
Labels: description

#8 add util functions
  src/utils/guessed-number.js
  src/utils/isEven.js
  src/utils/isEven.test.js
  src/utils/random-number.js
Labels: js

#9 add html
  index.html
Labels: html

#12 add readme
  README.md
  planning/screenshot-game.png
  planning/screenshot.jpg
Labels: description

#14 add index js
  src/index.js
  src/utils/random-number.js
Labels: js

#15 add a new feature and fix the issues
  css/index.css
  index.html
  src/index.js
Labels: html, css, js
